# Generated by Django 4.1.6 on 2023-02-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'permissions': [('view_not_moderated_announcement', 'Видеть немодерированные объявления')]},
        ),
    ]
