# Generated by Django 4.1.6 on 2023-02-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время публикации'),
        ),
    ]
